openAI:
  chatGPT:
    model: gpt-3.5-turbo
    api:
      key: REPLACE_WITH_YOUR_API_KEY
      url: https://api.openai.com/v1/chat/completions
    maxCompletions: 1
    temperature: 0
    maxTokens: 100
